on:
  push:
    branches:
    - main

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: windows-latest
  
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install from PSGallery
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module Az, azure.datafactory.tools
        Import-Module -Name azure.datafactory.tools
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: ADF Publish using JSON
      shell: pwsh
      run: |
        $SubscriptionName = '8bc23a88-43fa-43e2-8df6-33b565fb915f'
        Set-AzContext -Subscription $SubscriptionName
        $ResourceGroupName = 'RG-eri-adf-v1'
        $DataFactoryName = "eri-adf-uat"
        $Location = "EastUS"
        $RootFolder = "${{github.workspace}}"
        Publish-AdfV2FromJson -RootFolder "$RootFolder" -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" -Location "$Location"
