on:
  push:
    branches:
    - main

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: windows-latest
  
    steps:
    - name: Check out repository code
    - uses: actions/checkout@v4
    - name: Perform a Pester test from the command-line
      shell: pwsh
      run: Write-Output "Hello, World!"
