on:
  push:
    branches:
    - main

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: windows-latest
  
    steps:
    - uses: SQLPlayer.DataFactoryTools.PublishADF.PublishADFTask@2
      name: 'Publish ADF eri-adf-uat from JSON files'
      with:
        azureSubscription: eriSynapseConnV2
        ResourceGroupName: 'RG-eri-adf-v1'
        DataFactoryName: 'eri-adf-uat'
        DataFactoryCodePath: '${{github.workspace}}'
        Location: 'East US'
