name: Publish ADF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Publish ADF eri-adf-uat from JSON files
      uses: Azure/data-factory-tools@v2
      with:
        azureSubscription: eriSynapseConnV2
        ResourceGroupName: 'RG-eri-adf-v1'
        DataFactoryName: 'eri-adf-uat'
        DataFactoryCodePath: '${{ github.workspace }}'
        Location: 'East US'
